# Generated by Django 3.1 on 2020-11-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='todo text')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('priority', models.CharField(choices=[(1, '余裕'), (2, 'まあまあ'), (3, 'ぼちぼち'), (4, 'やばい'), (5, 'かなりやばい')], default='ぼちぼち', max_length=10)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
