# Generated by Django 3.1 on 2020-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(choices=[('余裕', '余裕'), ('まあまあ', 'まあまあ'), ('ぼちぼち', 'ぼちぼち'), ('やばい', 'やばい'), ('かなりやばい', 'かなりやばい')], default='ぼちぼち', max_length=10),
        ),
    ]
