# Generated by Django 3.1 on 2020-11-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20201114_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(1, '余裕'), (2, 'まあまあ'), (3, 'ぼちぼち'), (4, 'やばい'), (5, 'かなりやばい')], default='やばさレベル'),
        ),
    ]
