# Generated by Django 3.1 on 2020-11-14 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201114_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='priority',
        ),
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(choices=[(1, '余裕'), (2, 'まあまあ'), (3, 'ぼちぼち'), (4, 'やばい'), (5, 'かなりやばい')], default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='motivation',
            field=models.IntegerField(choices=[(1, '余裕'), (2, 'まあまあ'), (3, 'ぼちぼち'), (4, 'やばい'), (5, 'かなりやばい')], default=1),
        ),
        migrations.AddField(
            model_name='todo',
            name='progress',
            field=models.IntegerField(choices=[(1, '余裕'), (2, 'まあまあ'), (3, 'ぼちぼち'), (4, 'やばい'), (5, 'かなりやばい')], default=1),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(default='Todo', max_length=200, verbose_name='todo text'),
        ),
    ]
