# Generated by Django 3.1 on 2020-11-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20201115_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('余裕', '余裕'), ('まあまあ', 'まあまあ'), ('ぼちぼち', 'ぼちぼち'), ('やばい', 'やばい'), ('かなりやばい', 'かなりやばい')], default=1, max_length=20, verbose_name='importance'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='motivation',
            field=models.CharField(choices=[('余裕', '余裕'), ('まあまあ', 'まあまあ'), ('ぼちぼち', 'ぼちぼち'), ('やばい', 'やばい'), ('かなりやばい', 'かなりやばい')], default=1, max_length=20, verbose_name='motivation'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='progress',
            field=models.CharField(choices=[('余裕', '余裕'), ('まあまあ', 'まあまあ'), ('ぼちぼち', 'ぼちぼち'), ('やばい', 'やばい'), ('かなりやばい', 'かなりやばい')], default=1, max_length=20, verbose_name='progress'),
        ),
    ]
