# Generated by Django 3.1 on 2020-11-15 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20201115_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='importance',
            field=models.CharField(choices=[('レベル1---余裕', '余裕'), ('レベル2---まあまあ', 'まあまあ'), ('レベル3---ぼちぼち', 'ぼちぼち'), ('レベル4---やばい', 'やばい'), ('レベル5---かなりやばい', 'かなりやばい')], default=1, max_length=20, verbose_name='importance'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='motivation',
            field=models.CharField(choices=[('レベル1---余裕', '余裕'), ('レベル2---まあまあ', 'まあまあ'), ('レベル3---ぼちぼち', 'ぼちぼち'), ('レベル4---やばい', 'やばい'), ('レベル5---かなりやばい', 'かなりやばい')], default=1, max_length=20, verbose_name='motivation'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='progress',
            field=models.CharField(choices=[('レベル1---余裕', '余裕'), ('レベル2---まあまあ', 'まあまあ'), ('レベル3---ぼちぼち', 'ぼちぼち'), ('レベル4---やばい', 'やばい'), ('レベル5---かなりやばい', 'かなりやばい')], default=1, max_length=20, verbose_name='progress'),
        ),
    ]
